//REGISTER USERS
export const SIGNUP_NEW_USER = "SIGNUP_NEW_USER";
export const DELETE_SIGNUP_DATA  = "DELETE_SIGNUP_DATA";
// AUTH Constants
export const FETCH_TOKEN = "FETCH_TOKEN";
export const FETCH_TOKEN_FAILED = "FETCH_TOKEN_FAILED";
export const TOKEN_REMOVE = "TOKEN_REMOVE";
export const FETCH_USER = "FETCH_USER";
export const GET_USERINFO = "GET_USERINFO";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PHONENO = "UPDATE_PHONENO";
export const UPDATE_PROFILEPIC = "UPDATE_PROFILEPIC";
export const DELETE_USER = "DELETE_USER";

//MENU CATEGORY Constants  
export const GET_CATEGORIES = "GET_CATEGORIES";

//MENU CATEGORYMEALS Constants  
export const GET_CATEGORY_MEALS = "GET_CATEGORY_MEALS";
export const GET_MENU_CATEGORY_MEALS_BY_ID = "GET_MENU_CATEGORY_MEALS_BY_ID";



//SUBSCRIBES
export const SUBSCRIBE = "SUBSCRIBE";
export const GET_ACTIVE_SUBSCRIBERS = "GET_ACTIVE_SUBSCRIBERS";
export const GET_ALL_SUBSCRIBERS = "GET_ALL_SUBSCRIBERS";
export const DELETE_SUBSCRIBER = "DELETE_SUBSCRIBER";
export const SUBSCRIBED_FAILED = "SUBSCRIBED_FAILED";

// App NotificationS
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_NOTIFICATION_OFF = "TOGGLE_NOTIFICATION_OFF";

// QR 
// export const CREATE_QR_CODE = "CREATE_QR_CODE";
export const SCAN_QR = "SCAN_QR";
export const NOT_FOUND = "NOT_FOUND";